export const BrandLogo = "https://thumbs.dreamstime.com/b/food-delivery-logo-template-vector-icon-illustration-170869600.jpg";

export const RestaurantCardData = {
        "data": [
            {
                "brand_id": 175,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/a162d2a2-e387-4260-8a05-7d78d9647e68.JPG",
                "brand_name": "Makhani Darbar",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Delicious Curries and Gravies",
                "logo": "https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg",
                "main_offering": "North Indian",
                "slug": "makhani-darbar",
                "is_exclusive": 0,
                "sequence": 1,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 175,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 175,
                    "name": "Makhani Darbar",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/MPGOURFDQX4X.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/a162d2a2-e387-4260-8a05-7d78d9647e68.JPG",
                    "slug": "makhani-darbar"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 175,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 344,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 7987325,
                        "logo": "",
                        "coupon_code": "STEALDEAL",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 40,
                        "minimum_order_amount": 199,
                        "max_discount_limit_value": 80,
                        "tnc": "Min order of 199, Max discount of 80",
                        "brand_id": 344,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 40% off",
                        "coupon_short_description": "Get 40% off upto ₹80"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 344,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/60f1d93b-5f33-4c74-aa0e-931f024a9eea.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 26,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/f8a36d79-2ee2-4a3b-8ead-1bdfac5b0d4e.jpg",
                "brand_name": "Behrouz Biryani",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Handcrafted, Royal Biryanis",
                "logo": "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
                "main_offering": "Royal Biryani",
                "slug": "behrouz-biryani",
                "is_exclusive": 0,
                "sequence": 2,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 26,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 26,
                    "name": "Behrouz Biryani",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/AZQZ2LKXCP.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/f8a36d79-2ee2-4a3b-8ead-1bdfac5b0d4e.jpg",
                    "slug": "behrouz-biryani"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 26,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 8,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 8,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    },
                    {
                        "coupon_id": 8071646,
                        "logo": "",
                        "coupon_code": "FLAT150",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 150,
                        "minimum_order_amount": 449,
                        "max_discount_limit_value": null,
                        "tnc": "- Not applicable with Buy1Get1 FREE offers\n- Applicable on Behrouz & Ovenstory restaurants only",
                        "brand_id": 8,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹150 off",
                        "coupon_short_description": "Flat ₹150 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/c64ad241-2a56-4d68-b9c9-483b4009a9d6.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 20,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/80317ad8-4c45-4944-be73-71ca0b967602.jpg",
                "brand_name": "Faasos",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Indulgent wraps loaded with high protein fillings",
                "logo": "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
                "main_offering": "Faasos",
                "slug": "faasos",
                "is_exclusive": 0,
                "sequence": 3,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 20,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 20,
                    "name": "Faasos",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/KBD9B6BGSL.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/80317ad8-4c45-4944-be73-71ca0b967602.jpg",
                    "slug": "faasos"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 20,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 3,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 3,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/721cfdb8-d70b-4384-a1f6-d8070de8503a.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 24,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/6377e8bb-772d-411c-8ceb-b1f01752d745.jpg",
                "brand_name": "Sweet Truth",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Heart of Every Celebration.",
                "logo": "https://rp-media.faasos.io/catalog/images/R9KE96OI3LFG.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/R9KE96OI3LFG.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/R9KE96OI3LFG.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/R9KE96OI3LFG.jpeg",
                "main_offering": "Desserts",
                "slug": "sweet-truth",
                "is_exclusive": 0,
                "sequence": 4,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 24,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 24,
                    "name": "Sweet Truth",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/R9KE96OI3LFG.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/6377e8bb-772d-411c-8ceb-b1f01752d745.jpg",
                    "slug": "sweet-truth"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 24,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 83,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 83,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/312b2cb3-505c-4cfc-ae68-bb6a0168338d.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 30,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/21ba138f-ca35-4b8c-8779-80508d631dab.jpg",
                "brand_name": "The Good Bowl",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Delicious Bowl Meals - Hygienic & Safe",
                "logo": "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
                "main_offering": "Rice Bowl",
                "slug": "the-good-bowl",
                "is_exclusive": 0,
                "sequence": 5,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 30,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 30,
                    "name": "The Good Bowl",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/7BLOJN54GE.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/21ba138f-ca35-4b8c-8779-80508d631dab.jpg",
                    "slug": "the-good-bowl"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 30,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 106,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 106,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/0d233d84-6b33-46fc-aa79-73f46eb1deac.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 27,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/d00d9d7d-9a80-408c-8067-e92d77d8db17.jpg",
                "brand_name": "Lunchbox - Meals & Thalis",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Exciting meals perfect for one.",
                "logo": "https://rp-media.faasos.io/catalog/images/WP13U2FKYI8P.png",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/WP13U2FKYI8P.png",
                "background_url": "https://rp-media.faasos.io/catalog/images/WP13U2FKYI8P.png",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/WP13U2FKYI8P.png",
                "main_offering": "Homestyle Meals",
                "slug": "lunchbox",
                "is_exclusive": 0,
                "sequence": 6,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 27,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 27,
                    "name": "Lunchbox - Meals & Thalis",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/WP13U2FKYI8P.png",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/d00d9d7d-9a80-408c-8067-e92d77d8db17.jpg",
                    "slug": "lunchbox"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 27,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 93,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 93,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/504c1867-63c7-49d5-8b02-3d48ed95b830.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 25,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/74c67e72-dc99-4862-aea8-e2e4d9cb7dc9.jpg",
                "brand_name": "The Biryani Life",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Hyderabad & Lucknow Biryani experts",
                "logo": "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
                "main_offering": "Hyderabadi Biryani",
                "slug": "the-biryani-life",
                "is_exclusive": 0,
                "sequence": 7,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 25,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 25,
                    "name": "The Biryani Life",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/2JUXUZOAFH.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/74c67e72-dc99-4862-aea8-e2e4d9cb7dc9.jpg",
                    "slug": "the-biryani-life"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 25,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 108,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 108,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/af37cb30-54f5-4bc4-b0c7-e1eaf5df906f.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 31,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/bf483b98-1d1c-4aa2-b0c2-43f5b2175bd7.jpg",
                "brand_name": "Veg Meals by Lunchbox",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Satvik bhi, Delicious bhi",
                "logo": "https://rp-media.faasos.io/catalog/images/5HVFQ07MQ91Q.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/5HVFQ07MQ91Q.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/5HVFQ07MQ91Q.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/5HVFQ07MQ91Q.jpeg",
                "main_offering": "Veg Meals",
                "slug": "veg-meals-by-lunchbox",
                "is_exclusive": 0,
                "sequence": 8,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 31,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 31,
                    "name": "Veg Meals by Lunchbox",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/5HVFQ07MQ91Q.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/bf483b98-1d1c-4aa2-b0c2-43f5b2175bd7.jpg",
                    "slug": "veg-meals-by-lunchbox"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 31,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 46,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 46,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/66173489-aa75-4508-bcb1-0150eab12773.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 29,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/bc67fff1-4b52-4cc3-ac56-175569fcccbf.jpg",
                "brand_name": "Wendy's Burgers",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Stacked & packed for heavy duty",
                "logo": "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
                "main_offering": "Burger",
                "slug": "wendy-s",
                "is_exclusive": 0,
                "sequence": 9,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 29,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 29,
                    "name": "Wendy's Burgers",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/YGYOJ03TVA.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/bc67fff1-4b52-4cc3-ac56-175569fcccbf.jpg",
                    "slug": "wendy-s"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 29,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 165,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 165,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/a89babf6-2148-4818-84d5-36a0b7a43e1d.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 218,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/add46bcc-4635-4ea4-8f02-770268c391cf.jpg",
                "brand_name": "Thalaiva Biryani",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "logo": "https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg",
                "main_offering": "Biryani",
                "slug": "thalaiva-biryani",
                "is_exclusive": 0,
                "sequence": 10,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 218,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 218,
                    "name": "Thalaiva Biryani",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/UF4RZT7C8LJS.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/add46bcc-4635-4ea4-8f02-770268c391cf.jpg",
                    "slug": "thalaiva-biryani"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 218,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 373,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 7987325,
                        "logo": "",
                        "coupon_code": "STEALDEAL",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 40,
                        "minimum_order_amount": 199,
                        "max_discount_limit_value": 80,
                        "tnc": "Min order of 199, Max discount of 80",
                        "brand_id": 373,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 40% off",
                        "coupon_short_description": "Get 40% off upto ₹80"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 373,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/d0b82979-7fe6-40a7-86cd-ac568bad67bf.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 229,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/a03bcf3c-f0f1-4d5d-b0ad-9fde98a329d3.png",
                "brand_name": "Honest bowl",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "logo": "https://rp-media.faasos.io/catalog/images/NR1NWSYGYN5D.jpeg",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/NR1NWSYGYN5D.jpeg",
                "background_url": "https://rp-media.faasos.io/catalog/images/NR1NWSYGYN5D.jpeg",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/NR1NWSYGYN5D.jpeg",
                "main_offering": "Honest Bowls",
                "slug": "honest-bowl",
                "is_exclusive": 0,
                "sequence": 11,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 8080824,
                    "logo": "",
                    "coupon_code": "FIRSTTIME",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 50,
                    "minimum_order_amount": 349,
                    "max_discount_limit_value": 500,
                    "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                    "brand_id": 229,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 50% off",
                    "coupon_short_description": "Get 50% off upto ₹500"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 229,
                    "name": "Honest bowl",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/NR1NWSYGYN5D.jpeg",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/a03bcf3c-f0f1-4d5d-b0ad-9fde98a329d3.png",
                    "slug": "honest-bowl"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 8080824,
                        "logo": "",
                        "coupon_code": "FIRSTTIME",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 50,
                        "minimum_order_amount": 349,
                        "max_discount_limit_value": 500,
                        "tnc": "Get 50% off upto 500 on your 1st 3 orders above Rs. 349. Not applicable on buy1get1",
                        "brand_id": 229,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 50% off",
                        "coupon_short_description": "Get 50% off upto ₹500"
                    },
                    {
                        "coupon_id": 7155948,
                        "logo": "https://product-assets.faasos.io/eatsure_cms/production/cf793e09-03fa-40c8-b936-e73f98a17091.jpeg",
                        "coupon_code": "PARTY",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 25,
                        "minimum_order_amount": 599,
                        "max_discount_limit_value": 7500,
                        "tnc": "- Applicable on select brands only\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 376,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 25% off",
                        "coupon_short_description": "Get 25% off upto ₹7500"
                    },
                    {
                        "coupon_id": 7987325,
                        "logo": "",
                        "coupon_code": "STEALDEAL",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 40,
                        "minimum_order_amount": 199,
                        "max_discount_limit_value": 80,
                        "tnc": "Min order of 199, Max discount of 80",
                        "brand_id": 376,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 40% off",
                        "coupon_short_description": "Get 40% off upto ₹80"
                    },
                    {
                        "coupon_id": 8022222,
                        "logo": "",
                        "coupon_code": "SMALLBITE",
                        "coupon_type_id": 2,
                        "is_max_discount_limit": 0,
                        "discount_value": 40,
                        "minimum_order_amount": 149,
                        "max_discount_limit_value": null,
                        "tnc": "- Get ₹40 off on orders above ₹149\n- Not applicable with buy1get1 & already discounted products",
                        "brand_id": 376,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get FLAT ₹40 off",
                        "coupon_short_description": "Flat ₹40 off"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/47af7048-4d10-4078-b6ba-be5bb7434873.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            },
            {
                "brand_id": 47,
                "store_id": 10639,
                "client_source_id": 13,
                "banner_image_es": "https://product-assets.faasos.io/eatsure_cms/production/03925111-5d95-41ec-9a39-3ef82b1314b4.jpg",
                "brand_name": "Mad Over Donuts",
                "brand_start_time": "00:00:00",
                "brand_end_time": "23:59:00",
                "description": "Bite into happiness",
                "logo": "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
                "rectangle_logo": "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
                "background_url": "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
                "background_url_large": "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
                "main_offering": "Mad Over Donuts",
                "slug": "mad-over-donuts",
                "is_exclusive": 0,
                "sequence": 12,
                "minimum_order_amount": 0,
                "brand_delivery_fees": 0,
                "max_delivery_time": 0,
                "min_delivery_time": 0,
                "inclusive_mrp": 1,
                "is_opened": 0,
                "discount_info": {
                    "coupon_id": 7987325,
                    "logo": "",
                    "coupon_code": "STEALDEAL",
                    "coupon_type_id": 1,
                    "is_max_discount_limit": 1,
                    "discount_value": 40,
                    "minimum_order_amount": 179,
                    "max_discount_limit_value": 80,
                    "tnc": "Min order of 179, Max discount of 80",
                    "brand_id": 47,
                    "client_os": "WebApp-EatSure",
                    "coupon_description": "Get upto 40% off",
                    "coupon_short_description": "Get 40% off upto ₹80"
                },
                "sure_points_multiplier_data": {
                    "forward_mul_own": "1.00",
                    "forward_mul_thirdparty": "1.00",
                    "reverse_mul": "0.05",
                    "minimum_sure_points_value": 100,
                    "brand_id": 47,
                    "name": "Mad Over Donuts",
                    "logo_image": "https://rp-media.faasos.io/catalog/images/QF6PFHJGJM.png",
                    "banner_image": "https://product-assets.faasos.io/eatsure_cms/production/03925111-5d95-41ec-9a39-3ef82b1314b4.jpg",
                    "slug": "mad-over-donuts"
                },
                "coupons_with_best_promotion": [
                    {
                        "coupon_id": 7987325,
                        "logo": "",
                        "coupon_code": "STEALDEAL",
                        "coupon_type_id": 1,
                        "is_max_discount_limit": 1,
                        "discount_value": 40,
                        "minimum_order_amount": 179,
                        "max_discount_limit_value": 80,
                        "tnc": "Min order of 179, Max discount of 80",
                        "brand_id": 47,
                        "client_os": "WebApp-EatSure",
                        "coupon_description": "Get upto 40% off",
                        "coupon_short_description": "Get 40% off upto ₹80"
                    }
                ],
                "store_front_brand_image_url": "https://product-assets.faasos.io/eatsure_cms/production/f1ec4383-d71b-4fd6-b034-c75713923579.jpg",
                "storefront_brand_rating": null,
                "count_of_brand_rating": null
            }
        ]
}